Repository element-hq/element-call, pull requests merged in 2022-11, with the labels that each got.

#695 Fix missing tile bug
  src/room/useGroupCall.ts
  src/video-grid/VideoGrid.tsx
Labels: T-Defect

#706 Fix Walkie-Talkie mode in Safari
  src/settings/useMediaHandler.tsx
Labels: T-Defect

#717 Add config file for CD version
  .github/workflows/netlify-main.yaml
  config/element_io_develop.json
Labels: T-Task

#658 Add posthog Telemetry (Anonymity Logic + call duration telemetry)
  package.json
  src/ClientContext.tsx
  src/PosthogAnalytics.ts
  src/PosthogEvents.ts
  src/auth/LoginPage.tsx
  src/auth/RegisterPage.tsx
  src/config/ConfigOptions.ts
  src/room/GroupCallInspector.tsx
  src/room/GroupCallView.tsx
  src/room/InCallView.tsx
  src/room/useGroupCall.ts
  src/settings/SettingsModal.tsx
  src/settings/useSetting.ts
  yarn.lock
Labels: A-Telemetry-Posthog

#725 Create advanced section for telemetry checkbox
  public/locales/en-GB/app.json
  src/settings/SettingsModal.tsx
Labels: S-Minor, A-Telemetry-Posthog

#729 A couple of minor a11y fixes
  public/locales/en-GB/app.json
  src/Header.tsx
  src/button/CopyButton.tsx
Labels: T-Defect

#727 Fix close button on join call modal
  src/IncompatibleVersionModal.tsx
  src/Modal.tsx
  src/home/JoinExistingCallModal.tsx
  src/video-grid/VideoTileSettingsModal.tsx
Labels: T-Defect

#738 Don't check out group-call branch in build script
  scripts/dockerbuild.sh
Labels: T-Task

#728 Add aria-describedby associations
  src/input/Input.tsx
Labels: T-Defect

#747 Make room / call creation logging more accurate
  src/matrix-utils.ts
Labels: T-Task

#752 Add a 'waiting for video' state to media tiles
  package.json
  public/locales/en-GB/app.json
  src/room/GroupCallView.tsx
  src/room/InCallView.tsx
  src/video-grid/VideoGrid.stories.tsx
  src/video-grid/VideoTile.tsx
  src/video-grid/VideoTileContainer.tsx
  yarn.lock
Labels: T-Enhancement

#756 Put rageshake request ID in title of debug log submission
  src/settings/submit-rageshake.ts
Labels: T-Task

#763 Fix click leaking through to DOM element underneath
  src/ListBox.tsx
Labels: T-Defect
