Repository element-hq/element-call, pull requests merged in 2022-09, with the labels that each got.

#564 Fix bug where additional group calls could be created
  package.json
  src/room/useLoadGroupCall.ts
  yarn.lock
Labels: T-Defect

#567 Use new method to wait until a room is ready for group calls
  package.json
  src/room/useLoadGroupCall.ts
  yarn.lock
Labels: T-Defect

#568 Log ID instead of object
  src/room/useLoadGroupCall.ts
Labels: T-Task

#574 Prepare for integration into Element Web
  package.json
  src/ClientContext.tsx
  src/LazyEventEmitter.ts
  src/matrix-utils.ts
  src/room/GroupCallView.tsx
  src/room/InCallView.tsx
  src/room/LobbyView.tsx
  src/room/PTTCallView.tsx
  src/room/RoomPage.tsx
  src/room/useRoomParams.ts
  src/widget.ts
  yarn.lock
Labels: T-Enhancement, X-Blocked

#579 Bump js-sdk dependency
  package.json
  yarn.lock
Labels: T-Defect

#580 Update js-sdk for exception fix
  package.json
  yarn.lock
Labels: T-Defect

#595 Fix scroll bug in spotlight view
  src/video-grid/VideoGrid.tsx
Labels: T-Defect

#601 Fix another cause of split-brain rooms
  src/room/useLoadGroupCall.ts
Labels: T-Defect

#602 Fix bug causing mic/webcam to remain open after call
  src/room/GroupCallView.tsx
Labels: T-Defect

#603 Clear storage after logout
  src/ClientContext.tsx
Labels: T-Defect

#609 Use device labels rather than IDs in widget API
  src/media-utils.ts
  src/room/GroupCallView.tsx
Labels: T-Defect
