Repository element-hq/element-call, pull requests merged in 2023-09, with the labels that each got.

#1418 Remove extra device request on the video preview page
  src/room/VideoPreview.tsx
Labels: T-Defect

#1421 Fix the mute icon being incorrect when using PTT
  src/room/InCallView.tsx
Labels: T-Defect

#1420 Add apple site association
  config/nginx.conf
  public/.well-known/assetlinks.json
  public/apple-app-site-association
Labels: T-Enhancement

#1348 Switch to the MatrixRTCSession layer in js-sdk
  package.json
  public/locales/en-GB/app.json
  src/IncompatibleVersionModal.tsx
  src/livekit/LivekitFocus.ts
  src/livekit/OpenIDLoader.tsx
  src/livekit/openIDSFU.ts
  src/livekit/useECConnectionState.ts
  src/livekit/useLiveKit.ts
  src/matrix-utils.ts
  src/room/GroupCallLoader.tsx
  src/room/GroupCallView.tsx
  src/room/InCallView.tsx
  src/room/RoomPage.tsx
  src/room/useActiveFocus.ts
  src/room/useGroupCall.ts
  src/room/useLoadGroupCall.ts
  src/room/useSentryGroupCallHandler.ts
  src/rtcSessionHelpers.ts
  src/useMatrixRTCSessionJoinState.ts
  src/useMatrixRTCSessionMemberships.ts
  src/widget.ts
  yarn.lock
Labels: T-Enhancement

#1410 Smooth Focus Switching
  src/room/InCallView.tsx
Labels: T-Enhancement

#1448 Add a prompt to launch Element X on mobile
  public/locales/en-GB/app.json
  src/UrlParams.ts
  src/room/AppSelectionModal.module.css
  src/room/AppSelectionModal.tsx
  src/room/RoomPage.tsx
Labels: X-Blocked

#1479 Small refactor of URLParams stuff
  src/UrlParams.ts
  src/initializer.tsx
  src/room/RoomPage.tsx
  src/widget.ts
  test/UrlParams-test.ts
Labels: T-Task

#1480 Lint the test files
  .eslintrc.cjs
Labels: T-Task

#1507 Add nightly & main app to assetlinks
  public/.well-known/assetlinks.json
Labels: T-Enhancement

#1529 Use the room ID as the react key
  src/home/CallList.tsx
Labels: T-Defect

#1530 Don't auto create calls from visiting the URL
  public/locales/en-GB/app.json
  src/room/GroupCallLoader.tsx
  src/room/useLoadGroupCall.ts
Labels: T-Defect

#1534 Fix a type
  src/home/useGroupCallRooms.ts
Labels: T-Task

#1533 Include the room name in the generated URL
  src/home/CallList.tsx
  src/home/RegisteredView.tsx
  src/home/UnauthenticatedView.tsx
  src/matrix-utils.ts
  src/room/AppSelectionModal.tsx
  src/room/GroupCallView.tsx
  src/room/ShareModal.tsx
Labels: T-Enhancement

#1546 Fix layout toggle on safari
  src/room/LayoutToggle.module.css
Labels: T-Defect

#1552 Better error for browsers that don't support e2ee
  public/locales/en-GB/app.json
  src/room/GroupCallView.tsx
Labels: T-Defect

#1557 Fix race where app would be opened with no e2ee key
  src/e2ee/sharedKeyManagement.ts
  src/room/AppSelectionModal.tsx
Labels: T-Defect

#1566 Capture livekit's logs in rageshakes
  src/livekit/useLiveKit.ts
  src/main.tsx
Labels: T-Defect

#1569 Bump js-sdk
  package.json
  yarn.lock
Labels: T-Task

#1570 Refactor useIsRoomE2EE
  src/e2ee/sharedKeyManagement.ts
  src/room/AppSelectionModal.tsx
  src/room/GroupCallView.tsx
  src/room/RoomPage.tsx
Labels: T-Task

#1573 Don't always try to join rooms
  src/room/useLoadGroupCall.ts
Labels: T-Defect

#1577 Revert "Capture livekit's logs in rageshakes"
  src/livekit/useLiveKit.ts
  src/main.tsx
Labels: T-Defect

#1592 Use the loglevel library's extensions
  .eslintrc.cjs
  src/FullScreenView.tsx
  src/auth/RegisterPage.tsx
  src/auth/useRecaptcha.ts
  src/home/RegisteredView.tsx
  src/home/UnauthenticatedView.tsx
  src/main.tsx
  src/matrix-utils.ts
  src/profile/useProfile.ts
  src/room/RoomAuthView.tsx
  src/room/RoomPage.tsx
  src/room/VideoPreview.tsx
  src/settings/rageshake.ts
  src/settings/submit-rageshake.ts
  src/video-grid/VideoGrid.tsx
Labels: T-Task
