Repository element-hq/element-call, pull requests merged in 2023-04, with the labels that each got.

#980 Add displayname on call spans
  config/otel_dev/collector-gateway.yaml
  src/otel/OTelGroupCallMembership.ts
Labels: T-Enhancement

#982 Include booleans in flattened OpenTelemetry object
  src/otel/OTelGroupCallMembership.ts
Labels: T-Defect

#981 Move call events to the call span
  src/otel/OTelGroupCallMembership.ts
Labels: T-Enhancement

#974 Add webrtc metric to OTel
  package.json
  src/otel/OTelGroupCallMembership.ts
  src/otel/ObjectFlattener.ts
  src/otel/otel.ts
  src/room/useGroupCall.ts
  test/otel/ObjectFlattener-test.ts
  yarn.lock
Labels: T-Task

#984 Add OpenTelemetry events for PeerConnection state changes / errors
  package.json
  src/otel/OTelCall.ts
  src/otel/OTelGroupCallMembership.ts
  yarn.lock
Labels: T-Enhancement

#985 Fix exception when loading PostHog
  src/ClientContext.tsx
  src/analytics/PosthogAnalytics.ts
  src/otel/OTelGroupCallMembership.ts
Labels: T-Defect

#988 Allow different OpenTelemetry collectors to be enabled/disabled
  src/otel/otel.ts
Labels: T-Task

#986 separate summary report from stats report
  package.json
  src/otel/OTelGroupCallMembership.ts
  yarn.lock
Labels: T-Task

#991 Add tiny release notes script
  scripts/reformat-release-notes.py
Labels: T-Task

#992 Add posthog event for summary report
  src/analytics/OtelPosthogExporter.ts
Labels: T-Task

#1000 Add jitter in webrtc stats
  package.json
  test/otel/ObjectFlattener-test.ts
  yarn.lock
Labels: T-Task

#1002 Fix PostHog in embedded mode
  src/room/GroupCallView.tsx
Labels: T-Defect

#1007 Use microseconds in the rageshake exporter
  src/analytics/RageshakeSpanProcessor.ts
Labels: T-Defect

#1009 Add new calculation of received media stats
  package.json
  yarn.lock
Labels: T-Task

#1016 Add .gz extension to to traces.json
  src/settings/submit-rageshake.ts
Labels: T-Task

#1017 Use the native ResizeObserver where available
  src/video-grid/VideoGrid.tsx
Labels: T-Task

#1022 Fix audio mute on window blur
  src/useCallViewKeyboardShortcuts.ts
Labels: T-Defect

#1020 Add the event name to the rageshake span processor export
  src/analytics/RageshakeSpanProcessor.ts
Labels: T-Task

#1024 End spans when calls are replaced by a different call
  src/otel/OTelGroupCallMembership.ts
Labels: T-Defect

#1025 Remove the console exporter
  src/otel/otel.ts
Labels: T-Task

#1019 Make webrtc stats configurable
  package.json
  src/room/useLoadGroupCall.ts
  yarn.lock
Labels: T-Task

#1030 Include org.matrix.call events in sent events for OTel
  src/otel/OTelGroupCallMembership.ts
Labels: T-Defect
