Repository element-hq/element-call, pull requests merged in 2023-11, with the labels that each got.

#1881 Update js-sdk for per-participant key rotation
  package.json
  yarn.lock
Labels: T-Enhancement

#1896 Revert per-sender keys
  package.json
  src/UrlParams.ts
  src/e2ee/e2eeType.ts
  src/e2ee/matrixKeyProvider.ts
  src/home/RegisteredView.tsx
  src/home/UnauthenticatedView.tsx
  src/livekit/useLiveKit.ts
  src/matrix-utils.ts
  src/room/GroupCallView.tsx
  src/room/InCallView.tsx
  src/rtcSessionHelpers.ts
  src/widget.ts
  yarn.lock
Labels: T-Task

#1891 Make E2EEConfig required
  src/livekit/useLiveKit.ts
  src/room/GroupCallView.tsx
  src/room/InCallView.tsx
Labels: T-Task

#1892 Keep screenshares when switching focus
  src/livekit/useECConnectionState.ts
  src/livekit/useLiveKit.ts
  src/room/InCallView.tsx
Labels: T-Defect

#1905 Prepare for migration from Weblate to Localazy
  i18next-parser.config.ts
  public/locales/de/app.json
  public/locales/el/app.json
  public/locales/en-GB/app.json
  public/locales/es/app.json
  public/locales/et/app.json
  public/locales/fr/app.json
  public/locales/id/app.json
  public/locales/it/app.json
  public/locales/lv/app.json
  public/locales/pl/app.json
  public/locales/ru/app.json
  public/locales/sk/app.json
  public/locales/sv/app.json
  public/locales/uk/app.json
  public/locales/zh-Hans/app.json
  public/locales/zh-Hant/app.json
  src/@types/i18next.d.ts
  src/TranslatedError.ts
  src/initializer.tsx
  tsconfig.json
Labels: T-Task

#1903 Update js-sdk
  package.json
  yarn.lock
Labels: T-Defect

#1910 Fix joining calls with no media permission
  src/livekit/useECConnectionState.ts
  src/livekit/useLiveKit.ts
  src/room/VideoPreview.tsx
Labels: T-Defect

#1902 Hide rooms we don't have the key for in recents list
  src/UrlParams.ts
  src/e2ee/sharedKeyManagement.ts
  src/home/useGroupCallRooms.ts
  src/matrix-utils.ts
Labels: T-Defect
