Repository element-hq/element-call, pull requests merged in 2025-03, with the labels that each got.

#3062 Reduce redundant calculations of display name map
  src/state/CallViewModel.ts
Labels: A-Performance

#3015 Use the New MatrixRTCSession MembershipManager
  locales/en/app.json
  package.json
  src/room/GroupCallView.tsx
  src/rtcSessionHelpers.test.ts
  src/rtcSessionHelpers.ts
  src/settings/DeveloperSettingsTab.tsx
  src/settings/settings.ts
  src/settings/submit-rageshake.ts
  src/utils/errors.ts
  src/utils/matrix.ts
  yarn.lock
Labels: X-Release-Blocker

#3066 Cache calls to removeHiddenChars() to fix performance bottleneck in Safari
  src/utils/displayname-integration.test.ts
  src/utils/displayname.ts
Labels: backport candidate

#3067 New Membership Manager js-sdk develop
  package.json
  tsconfig.json
  yarn.lock
Labels: backport candidate

#3080 Pin matrix-js-sdk to a specific commit
  package.json
  yarn.lock
Labels: backport candidate

#3058 refactor: Centralize group call errors in custom GroupCallErrorBoundary
  src/RichError.tsx
  src/livekit/useECConnectionState.test.tsx
  src/livekit/useECConnectionState.ts
  src/room/GroupCallErrorBoundary.test.tsx
  src/room/GroupCallErrorBoundary.tsx
  src/room/GroupCallView.tsx
  src/room/__snapshots__/GroupCallErrorBoundary.test.tsx.snap
  src/utils/errors.ts
Labels: backport candidate

#3063 Error: use a close button instead of go to home when in widget mode
  src/App.tsx
  src/ClientContext.tsx
  src/ErrorView.tsx
  src/FullScreenView.tsx
  src/RichError.tsx
  src/home/HomePage.tsx
  src/livekit/useECConnectionState.test.tsx
  src/room/GroupCallErrorBoundary.test.tsx
  src/room/GroupCallErrorBoundary.tsx
  src/room/GroupCallView.tsx
  src/room/RoomPage.tsx
  src/room/__snapshots__/GroupCallErrorBoundary.test.tsx.snap
Labels: backport candidate

#3088 Separate widget-only URL parameters in the documentation
  docs/url-params.md
Labels: A-Developer-Experience

#3108 Rename built artifact name on v0.8.0 release branch for compatibility with Netlify PR preview
  .github/workflows/build-and-publish-docker.yaml
  .github/workflows/build-element-call.yaml
  .github/workflows/deploy-to-netlify.yaml
  .github/workflows/publish.yaml
Labels: A-Developer-Experience

#3086 Publish embedded package for releases of Element Call
  .github/workflows/publish-embedded-packages.yaml
  .github/workflows/publish.yaml
  README.md
  docs/embedded-standalone.md
  docs/url-params.md
  embedded/android/.gitattributes
  embedded/android/.gitignore
  embedded/android/gradle.properties
  embedded/android/gradle/libs.versions.toml
  embedded/android/gradle/wrapper/gradle-wrapper.jar
  embedded/android/gradle/wrapper/gradle-wrapper.properties
  embedded/android/gradlew
  embedded/android/gradlew.bat
  embedded/android/lib/build.gradle.kts
  embedded/android/publish_android_package.sh
  embedded/android/settings.gradle
  embedded/ios/.gitignore
  embedded/ios/LICENSE-AGPL-3.0
  embedded/ios/LICENSE-COMMMERCIAL
  embedded/ios/Package.swift
  embedded/ios/README.md
  embedded/ios/Sources/EmbeddedElementCall/EmbeddedElementCall.swift
  embedded/web/LICENSE-AGPL-3.0
  embedded/web/LICENSE-COMMERCIAL
  embedded/web/README.md
  embedded/web/package.json
Labels: T-Enhancement

#3118 Fix join errors mistakenly showing a generic error screen
  src/livekit/openIDSFU.ts
  src/room/GroupCallView.test.tsx
  src/room/GroupCallView.tsx
  src/useErrorBoundary.test.tsx
  src/useErrorBoundary.ts
  src/utils/test.ts
Labels: backport candidate

#3124 Fix compilation error when trying to use SwiftPM embedded package
  .github/workflows/publish-embedded-packages.yaml
  embedded/ios/Package.swift
Labels: T-Defect, A-Testing, backport candidate

#3133 Backport: Use correct rageshake URL when running in embedded package
  src/settings/submit-rageshake.ts
Labels: T-Defect

#3134 Show URL params and environment variables in developer tab
  locales/en/app.json
  src/settings/DeveloperSettingsTab.tsx
Labels: A-Developer-Experience

#3135 Rename EULA to SSLA
  config/config.devenv.json
  config/config.sample.json
  locales/en/app.json
  src/auth/RegisterPage.tsx
  src/config/ConfigOptions.ts
  src/home/UnauthenticatedView.tsx
  src/room/RoomAuthView.tsx
Labels: T-Enhancement, T-Breaking-Change

#3136 Fix example JWT service .well-known endpoints in self-hosting.md
  docs/self-hosting.md
Labels: T-Defect

#3144 Expose version string in embedded SwiftPM and AAR
  .github/workflows/publish-embedded-packages.yaml
  embedded/android/lib/src/main/kotlin/io/element/android/call/embedded/Version.kt
  embedded/ios/Sources/EmbeddedElementCall/EmbeddedElementCall.swift
Labels: T-Enhancement

#3132 Use correct rageshake URL when running in embedded package + tests
  src/settings/SettingsModal.tsx
  src/settings/submit-rageshake.test.ts
  src/settings/submit-rageshake.ts
  src/settings/useSubmitRageshake.test.tsx
Labels: T-Defect, backport-candidate
