Repository element-hq/element-call, pull requests merged in 2025-09, with the labels that each got.

#3400 Prefer showing the reaction button at small screen widths
  playwright/create-call.spec.ts
  src/room/InCallView.module.css
Labels: PR-Improvement

#3217 Add drum/joke reaction
  src/button/__snapshots__/ReactionToggleButton.test.tsx.snap
  src/reactions/index.ts
  src/sound/LICENCE.md
  src/sound/reactions/baduntss.mp3
  src/sound/reactions/baduntss.ogg
Labels: PR-Feature

#3486 Fix the interactivity of buttons while reconnecting or in earpiece mode
  backend/dev_nginx.conf
  backend/playwright_homeserver.yaml
  playwright/fixtures/widget-user.ts
  playwright/reconnect.spec.ts
  playwright/widget/simple-create.spec.ts
  src/Overlay.module.css
  src/Toast.tsx
  src/reactions/RaisedHandIndicator.tsx
  src/room/EarpieceOverlay.module.css
  src/room/EarpieceOverlay.tsx
  src/room/InCallView.tsx
  src/room/__snapshots__/InCallView.test.tsx.snap
  src/tile/GridTile.test.tsx
  src/tile/GridTile.tsx
  src/tile/MediaView.test.tsx
  src/tile/MediaView.tsx
  src/tile/SpotlightTile.test.tsx
  src/tile/SpotlightTile.tsx
Labels: PR-Bug-Fix

#3495 Log when a track is unpublished or runs into an error
  src/livekit/useLivekit.ts
Labels: T-Task

#3502 Fix: never stop ring feedback on the sender side.
  src/state/CallViewModel.test.ts
  src/state/CallViewModel.ts
Labels: PR-Bug-Fix
