Repository element-hq/element-call, pull requests merged in 2025-05, with the labels that each got.

#3244 Fix release notes
  .github/release.yml
Labels: PR-Task

#3247 Keep the HTML lang attribute in sync with the i18next language
  src/initializer.tsx
Labels: PR-Improvement

#3258 Remove patched version of WebCodecs types
  knip.ts
  package.json
  src/@types/dom-mediacapture-transform.d.ts
  src/@types/dom-webcodecs.d.ts
  yarn.lock
Labels: PR-Task

#3239 Developer option to mute all audio
  locales/en/app.json
  src/room/CallEventAudioRenderer.tsx
  src/room/GroupCallView.tsx
  src/room/InCallView.tsx
  src/room/ReactionAudioRenderer.tsx
  src/settings/DeveloperSettingsTab.tsx
  src/settings/settings.ts
  src/useAudioContext.tsx
Labels: PR-Developer-Experience

#3208 Fix to-device encryption info label
  src/livekit/useLivekit.ts
  src/room/InCallView.test.tsx
  src/room/InCallView.tsx
  src/room/ReactionAudioRenderer.test.tsx
  src/room/__snapshots__/InCallView.test.tsx.snap
  src/settings/SettingsModal.tsx
  src/settings/settings.ts
  src/useAudioContext.test.tsx
  src/useAudioContext.tsx
  src/utils/test.ts
Labels: PR-Bug-Fix

#3255 Fix connection leaks: Ensure that any pending connection open are cancelled/undo when ActiveCall is unmounted
  src/livekit/useECConnectionState.test.tsx
  src/livekit/useECConnectionState.ts
  src/livekit/useLivekit.ts
  src/room/GroupCallView.tsx
  src/room/InCallView.tsx
  src/room/LobbyView.tsx
  src/utils/abortHandle.ts
Labels: X-Release-Blocker, PR-Bug-Fix

#3269 Backport: Fix connection leaks: Ensure that any pending connection open are cancelled/undo when ActiveCall is unmounted (#3255)
  src/livekit/useECConnectionState.test.tsx
  src/livekit/useECConnectionState.ts
  src/livekit/useLiveKit.ts
  src/room/GroupCallView.tsx
  src/room/InCallView.tsx
  src/room/LobbyView.tsx
  src/utils/abortHandle.ts
Labels: PR-Bug-Fix

#3249 Add custom audio renderer for iPhone earpiece and only render joined participants
  locales/en/app.json
  playwright/access.spec.ts
  src/UserMenu.tsx
  src/livekit/MatrixAudioRenderer.test.tsx
  src/livekit/MatrixAudioRenderer.tsx
  src/livekit/MediaDevicesContext.tsx
  src/room/InCallView.test.tsx
  src/room/InCallView.tsx
  src/room/MuteStates.test.tsx
  src/room/__snapshots__/InCallView.test.tsx.snap
  src/settings/DeveloperSettingsTab.tsx
  src/settings/DeviceSelection.tsx
  src/settings/SettingsModal.tsx
  src/settings/settings.ts
  src/useAudioContext.test.tsx
  src/useAudioContext.tsx
  src/utils/test.ts
Labels: PR-Feature

#3261 Docker-compose: do not access ports <443
  backend/dev_nginx.conf
  dev-backend-docker-compose.yml
Labels: PR-Developer-Experience

#3267 Update RTCSession configuration to non deprecated names.
  package.json
  src/e2ee/matrixKeyProvider.ts
  src/rtcSessionHelpers.ts
  tsconfig.json
  yarn.lock
Labels: X-Blocked, PR-Task

#3277 Bump js-sdk to support to-device driver unsupported fallback.
  package.json
  yarn.lock
Labels: PR-Improvement

#3177 Improve the reliability of state changes in widget mode
  package.json
  yarn.lock
Labels: backport-candidate, PR-Improvement

#3281 Improve the reliability of state changes in widget mode
  package.json
  yarn.lock
Labels: PR-Improvement

#3285 Reset to develop branch of matrix-js-sdk
  package.json
  yarn.lock
Labels: dependencies, backport-candidate

#3270 Audio device controls for mobile native audio device selection
  docs/controls.md
  docs/url-params.md
  locales/en/app.json
  package.json
  src/UrlParams.ts
  src/controls.ts
  src/livekit/MediaDevicesContext.tsx
  src/livekit/useLivekit.ts
  src/room/GroupCallView.tsx
  src/room/InCallView.tsx
  src/room/MuteStates.test.tsx
  src/room/MuteStates.ts
  src/settings/DeviceSelection.tsx
  src/settings/SettingsModal.tsx
  src/settings/settings.ts
  src/state/MuteAllAudioModel.test.ts
  src/state/MuteAllAudioModel.ts
  src/useAudioContext.test.tsx
  yarn.lock
Labels: backport-candidate, PR-Feature

#3288 Audio device controls for mobile native audio device selection
  docs/controls.md
  docs/url-params.md
  locales/en/app.json
  package.json
  src/UrlParams.ts
  src/controls.ts
  src/livekit/MediaDevicesContext.tsx
  src/livekit/useLivekit.ts
  src/room/GroupCallView.tsx
  src/room/InCallView.tsx
  src/room/MuteStates.test.tsx
  src/room/MuteStates.ts
  src/settings/DeviceSelection.tsx
  src/settings/SettingsModal.tsx
  src/settings/settings.ts
  src/state/MuteAllAudioModel.test.ts
  src/state/MuteAllAudioModel.ts
  src/useAudioContext.test.tsx
  yarn.lock
Labels: PR-Feature

#3290 Disable device switching when in controlled audio devices mode and non `update_state` widget driver compatibility
  src/livekit/useLivekit.ts
  src/useAudioContext.test.tsx
  src/useAudioContext.tsx
  yarn.lock
Labels: PR-Improvement

#3293 Fix creating two lk rooms if there is no local store setup (fixes a resulting disconnect bug)
  src/e2ee/sharedKeyManagement.ts
  src/livekit/useLivekit.ts
  src/main.tsx
  src/useLocalStorage.ts
Labels: PR-Bug-Fix

#3295 Only use ios platform logic when in controlled media device condition
  src/settings/SettingsModal.tsx
Labels: PR-Bug-Fix

#3300 Run the 'Prevent blocked' check whenever a PR branch is updated
  .github/workflows/blocked.yaml
Labels: PR-Task
