Repository element-hq/element-call, pull requests merged in 2025-06, with the labels that each got.

#3313 Upgrade Android publishing to use Maven Central Portal
  embedded/android/gradle/libs.versions.toml
  embedded/android/lib/build.gradle.kts
Labels: PR-Task

#3302 Leave issue refactor
  src/e2ee/sharedKeyManagement.ts
  src/home/useGroupCallRooms.ts
  src/livekit/useLivekit.ts
  src/room/GroupCallView.tsx
  src/room/InCallView.tsx
  src/useLocalStorage.ts
Labels: PR-Task

#3314 Fix react errors in settings tab
  src/settings/FeedbackSettingsTab.tsx
  src/tabs/Tabs.tsx
Labels: PR-Bug-Fix

#3316 Avoid reactivity bugs in how we track external state
  src/room/GroupCallView.test.tsx
  src/room/useActiveFocus.ts
  src/room/useRoomName.ts
  src/room/useRoomState.ts
  src/useEvents.test.tsx
  src/useEvents.ts
  src/useLocalStorage.test.tsx
  src/useLocalStorage.ts
  src/useMatrixRTCSessionJoinState.ts
  src/useMatrixRTCSessionMemberships.ts
  src/useMediaQuery.ts
  src/utils/test.ts
Labels: PR-Bug-Fix

#3204 Build Docker image on slim base
  .github/workflows/test.yaml
  Dockerfile
  playwright.config.ts
  playwright/fixtures/widget-user.ts
  scripts/playwright-webserver-command.sh
Labels: docker build, PR-Improvement

#3309 add onAudioPlaybackStarted callback for controls
  docs/controls.md
  src/controls.ts
  src/livekit/MatrixAudioRenderer.tsx
  src/useAudioContext.tsx
Labels: PR-Improvement

#3326 add tools section to self-hosting guide and adding Matrixtester to it
  docs/self-hosting.md
Labels: PR-Documentation

#3323 Add developer build mode to GitHub action build-element-call.yaml
  .github/workflows/build-element-call.yaml
  .github/workflows/build.yaml
  package.json
  vite.config.js
Labels: PR-Developer-Experience, development build

#3332 Apply new timing constants to MatrixRTC session
  config/config.devenv.json
  config/config.sample.json
  config/config_netlify_preview.json
Labels: PR-Improvement

#3333 bump js-sdk to latest develop (containing a fix for membership manager resend join event)
  yarn.lock
Labels: PR-Bug-Fix

#3351 Mute camera in earpice mode
  src/MediaDevicesContext.ts
  src/room/MuteStates.ts
Labels: PR-Feature

#3362 Fix white borders in PiP mode android (Fix scroll issues in small documents)
  src/index.css
  src/room/GroupCallView.tsx
Labels: PR-Bug-Fix

#3347 Earpiece switcher and overlay
  docs/url-params.md
  locales/en/app.json
  src/App.tsx
  src/AppBar.module.css
  src/AppBar.test.tsx
  src/AppBar.tsx
  src/FullScreenView.tsx
  src/UrlParams.test.ts
  src/UrlParams.ts
  src/__snapshots__/AppBar.test.tsx.snap
  src/controls.ts
  src/home/RegisteredView.tsx
  src/home/UnauthenticatedView.tsx
  src/index.css
  src/room/CallEndedView.tsx
  src/room/EarpieceOverlay.module.css
  src/room/EarpieceOverlay.tsx
  src/room/GroupCallView.test.tsx
  src/room/GroupCallView.tsx
  src/room/InCallView.module.css
  src/room/InCallView.test.tsx
  src/room/InCallView.tsx
  src/room/RoomAuthView.tsx
  src/room/RoomPage.tsx
  src/room/__snapshots__/InCallView.test.tsx.snap
  src/settings/DeviceSelection.tsx
  src/state/CallViewModel.test.ts
  src/state/CallViewModel.ts
  src/state/MediaDevices.ts
  src/tile/GridTile.module.css
  src/tile/MediaView.module.css
  src/utils/test-viewmodel.ts
  src/widget.ts
Labels: PR-Feature

#3337 Touch up some error screens
  locales/en/app.json
  src/ErrorView.module.css
  src/ErrorView.tsx
  src/room/GroupCallView.tsx
  src/room/__snapshots__/GroupCallErrorBoundary.test.tsx.snap
  src/utils/errors.ts
Labels: PR-Bug-Fix

#3369 Increase opacity of the EarpieceOverlay background for better visibility
  src/room/EarpieceOverlay.module.css
Labels: PR-Improvement
