Repository element-hq/element-call, pull requests merged in 2025-08, with the labels that each got.

#3428 Display a custom error for restricted SFU config error
  locales/en/app.json
  playwright/errors.spec.ts
  src/livekit/useECConnectionState.ts
  src/utils/errors.ts
Labels: T-Task

#3436 Reset LiveKit connection timeouts to their defaults
  src/livekit/useECConnectionState.ts
Labels: PR-Improvement

#3440 Improve Matrix site setup diagram
  docs/MSC4195_setup.drawio.png
Labels: PR-Documentation

#3445 Add intents for DM
  docs/url-params.md
  src/UrlParams.ts
Labels: PR-Improvement

#3443 Use `.ts` for remaining js config files
  .eslintrc.cjs
  i18next-parser.config.ts
  knip.ts
  src/livekit/BlurBackgroundTransformer.ts
  src/livekit/TrackProcessorContext.tsx
  vite-embedded.config.ts
  vite.config.ts
  vitest.config.ts
Labels: PR-Developer-Experience

#3455 Doc: Use new naming of jwt auth service
  README.md
  docs/Federated_Setup.drawio.png
  docs/MSC4195_setup.drawio.png
  docs/element_call_standalone.drawio.png
  docs/element_call_widget.drawio.png
  docs/self-hosting.md
Labels: PR-Documentation

#3453 Pause media tracks and show a message when reconnecting to MatrixRTC
  locales/en/app.json
  src/App.tsx
  src/AppBar.tsx
  src/Header.tsx
  src/Toast.tsx
  src/room/CallEventAudioRenderer.test.tsx
  src/room/GroupCallView.test.tsx
  src/room/GroupCallView.tsx
  src/room/InCallView.test.tsx
  src/room/InCallView.tsx
  src/room/__snapshots__/InCallView.test.tsx.snap
  src/state/CallViewModel.test.ts
  src/state/CallViewModel.ts
  src/state/MediaViewModel.ts
  src/tile/SpotlightTile.tsx
  src/utils/observable.test.ts
  src/utils/observable.ts
  src/utils/test-viewmodel.ts
  src/utils/test.ts
  yarn.lock
Labels: PR-Feature

#3463 Refine MatrixRTC connection wording
  src/state/CallViewModel.ts
Labels: PR-Task

#3464 Test sync loop status and membership status in reconnection test as well
  src/state/CallViewModel.test.ts
  src/utils/test.ts
Labels: PR-Task
