Repository element-hq/element-call, pull requests merged in 2025-04, with the labels that each got.

#3164 Fix lint and playwright errors caused by matrix-js-sdk/src import
  backend/ew.test.config.json
  dev-backend-docker-compose.yml
  playwright/fixtures/widget-user.ts
  playwright/global.d.ts
Labels: PR-Develeoper-Experience

#3163 Widget: Add missing to device permission for encryption keys
  src/widget.ts
Labels: T-Task

#3185 Add `RoomAndToDeviceKeyTransport`
  package.json
  src/room/InCallView.tsx
  src/settings/settings.ts
  yarn.lock
Labels: PR-Improvement

#3196 Explicitly set docker image version for releases
  .github/workflows/publish.yaml
Labels: T-Defect

#3197 Set the correct license on docker images
  .github/workflows/build-and-publish-docker.yaml
Labels: docker build

#3203 Improve tagging of Release versions of platform specific embedded packages
  .github/workflows/publish-embedded-packages.yaml
  embedded/android/lib/build.gradle.kts
Labels: backport-candidate

#3171 Add PR- label requirement action
  .github/workflows/changelog-label.yml
Labels: PR-Developer-Experience

#3210 Add a .links.temp-disabled.yaml state explicitly for when the pre-commit hook disabled the yaml.
  .githooks/post-commit
  .githooks/pre-commit
  .gitignore
Labels: PR-Developer-Experience

#3209 Backport: Fix to-device encryption info label
  src/room/InCallView.tsx
Labels: PR-Bug-Fix

#3215 add information about required synapse listeners
  docs/self-hosting.md
Labels: PR-Documentation

#3222 Revert livekit-client to 2.10.0
  package.json
  yarn.lock
Labels: backport-candidate, PR-Task

#3226 Fix MatrixRTC js-sdk logs in rageshakes
  package.json
  src/settings/rageshake.ts
  yarn.lock
Labels: PR-Improvement

#3224 Set `ratchetWindowSize` to > 0 enable rachet compatibility.
  src/e2ee/matrixKeyProvider.ts
Labels: backport-candidate, PR-Improvement

#3229 Return to latest livekit-client version (2.11.3)
  package.json
  yarn.lock
Labels: dependencies, backport-candidate

#3236 Fix syntax highlighting of Nginx snippets
  docs/self-hosting.md
Labels: PR-Documentation

#3237 Fix Playwright tests in Firefox
  package.json
  playwright/fixtures/widget-user.ts
  yarn.lock
Labels: PR-Developer-Experience

#2812 Add background blur feature for supported devices
  locales/en/app.json
  package.json
  src/@types/dom-mediacapture-transform.d.ts
  src/@types/dom-webcodecs.d.ts
  src/App.tsx
  src/livekit/BlurBackgroundTransformer.ts
  src/livekit/TrackProcessorContext.tsx
  src/livekit/useLiveKit.ts
  src/mediapipe/imageSegmenter/README.md
  src/mediapipe/imageSegmenter/selfie_segmenter.tflite
  src/room/GroupCallView.test.tsx
  src/room/LobbyView.tsx
  src/settings/SettingsModal.tsx
  src/settings/settings.ts
  yarn.lock
Labels: PR-Feature
