Repository element-hq/element-call, pull requests merged in 2025-07, with the labels that each got.

#3383 Fix bluetooth iOS issue (device auto switches from Bluetooth to speaker)
  src/livekit/useLivekit.ts
  src/room/MuteStates.ts
  src/state/CallViewModel.ts
  src/state/MediaDevices.ts
Labels: PR-Bug-Fix

#3398 Bump js-sdk dependency to have new encryption mgr
  yarn.lock
Labels: PR-Task

#3346 Create a type-level distinction between raw Observables and Behaviors
  .eslintrc.cjs
  src/button/ReactionToggleButton.tsx
  src/grid/Grid.tsx
  src/grid/OneOnOneLayout.tsx
  src/grid/SpotlightExpandedLayout.tsx
  src/grid/SpotlightPortraitLayout.tsx
  src/livekit/useLivekit.ts
  src/reactions/useReactionsSender.tsx
  src/room/GroupCallView.test.tsx
  src/room/GroupCallView.tsx
  src/room/InCallView.tsx
  src/room/ReactionsOverlay.tsx
  src/settings/SettingsModal.tsx
  src/settings/settings.ts
  src/state/Behavior.ts
  src/state/CallViewModel.test.ts
  src/state/CallViewModel.ts
  src/state/MediaDevices.ts
  src/state/MediaViewModel.ts
  src/state/MuteAllAudioModel.test.ts
  src/state/MuteAllAudioModel.ts
  src/state/ObservableScope.ts
  src/state/TileViewModel.ts
  src/tile/GridTile.test.tsx
  src/tile/GridTile.tsx
  src/tile/SpotlightTile.test.tsx
  src/tile/SpotlightTile.tsx
  src/useAudioContext.test.tsx
  src/useBehavior.ts
  src/utils/test.ts
Labels: PR-Task

#3408 Bump js-sdk resolved commit to the latest develop
  yarn.lock
Labels: PR-Task

#3248 Send notification events when starting a call
  docs/url-params.md
  src/UrlParams.ts
  src/rtcSessionHelpers.ts
  yarn.lock
Labels: PR-Feature

#3414 bump js-sdk to matrix-js-sdk 0ce944f3daa2c8926c673af33ae24e89b1e6796a
  yarn.lock
Labels: PR-Task

#3376 UrlParams: Intent system update, split into configuration and propreties
  src/UrlParams.test.ts
  src/UrlParams.ts
  src/room/MuteStates.test.tsx
Labels: PR-Developer-Experience

#3421 Request capability to send call notifications
  src/widget.ts
Labels: X-Release-Blocker, PR-Bug-Fix

#3415 Expose `delayed_leave_event_restart_local_timeout_ms` to `config.json`
  src/config/ConfigOptions.ts
  src/rtcSessionHelpers.ts
Labels: PR-Improvement

#3430 fix snapshot test following commit 007a50d
  dev-backend-docker-compose.yml
  src/room/__snapshots__/GroupCallErrorBoundary.test.tsx.snap
Labels: PR-Task
